/**
 * Generates native-boost.css: every design rule re-emitted with an
 * .et_pb_text_inner ancestor prefix, so inside Divi text modules the
 * design system always outranks Divi's own element rules (which sit at
 * class+element specificity and beat the design's bare class rules).
 *
 * Regenerate whenever the source stylesheets change:
 *   node gen-boost.mjs
 * The output is versioned and enqueued last; it cannot drift from the
 * design because it IS the design, re-scoped.
 */
import postcss from 'postcss';
import fs from 'node:fs';
import path from 'node:path';
import { here } from './common.mjs';

const cssDir = path.resolve(here, '../../../divi-child-integration/assets/css');
const SOURCES = ['pomdr-design.css', 'pomdr.css', 'a11y.css'];

// Selectors that must not be re-scoped: chrome, page furniture, Divi's own,
// element-only selectors (no class), and structural roots.
const SKIP = /(^|[^\w-])(html|body|:root)([^\w-]|$)|et_pb|et-vb|#site|#main-content|\.nav\b|\.action-bar|\.footer|\.a11y-|\.skip-link|\.drawer|\.hero\b|\.pt-|@/;
const ELEMENT_OK = /^(h[1-6]|p|ul|ol|li|blockquote|figure|figcaption|table|th|td|dl|dt|dd|hr|img|picture|strong|em|small)([\s.:>,[]|$)/;

const SYNTH = `
/* Synthetic base, (0,2,0) via :where: beats Divi's element rules inside
   text modules, ties every boosted design class rule and loads first, so
   all boosted rules outrank it. Headings deliberately absent (the design
   ships its own .et_pb_module h1-h6 rules). */
body.pom-native .et_pb_text :where(p, li, ol, ul, blockquote, figcaption) {
  font-size: inherit; line-height: inherit; font-family: inherit;
}
/* Mirror Divi's GLOBAL paragraph padding pair exactly (the reference
   standard): 1em bottom, zeroed on the last p of its parent. Divi's
   module-scoped variant uses :last-child, which misfires when a div
   follows the final paragraph; this restores last-of-type semantics. */
body.pom-native .et_pb_text :where(p) { padding-bottom: 1em; }
body.pom-native .et_pb_text :where(p:not(.has-background):last-of-type) { padding-bottom: 0; }
`;
let out = `/* GENERATED by scripts/native/fidelity/gen-boost.mjs. Do not edit.\n   Design rules re-scoped under body.pom-native: a uniform +1 class that\n   outranks Divi's module element styles while preserving the design's\n   own internal precedence (ancestor-class selectors stay alive). */\n` + SYNTH;

for (const file of SOURCES) {
  const p = path.join(cssDir, file);
  if (!fs.existsSync(p)) continue;
  const root = postcss.parse(fs.readFileSync(p, 'utf8'));
  const boosted = postcss.root();

  root.walkRules((rule) => {
    if (rule.parent && rule.parent.type === 'atrule' && /keyframes/i.test(rule.parent.name)) return;
    const sels = rule.selectors.filter((s) => (s.includes('.') || ELEMENT_OK.test(s.trim())) && !SKIP.test(s));
    if (!sels.length) return;
    const clone = rule.clone();
    clone.selectors = sels.map((s) => `body.pom-native ${s.trim()}`);
    // Preserve @media wrappers.
    if (rule.parent && rule.parent.type === 'atrule') {
      const media = postcss.atRule({ name: rule.parent.name, params: rule.parent.params });
      media.append(clone);
      boosted.append(media);
    } else {
      boosted.append(clone);
    }
  });

  out += `\n/* ---- from ${file} ---- */\n` + boosted.toString() + '\n';
}

const dest = path.join(cssDir, 'native-boost.css');
fs.writeFileSync(dest, out);
console.log(`native-boost.css: ${(out.length / 1024).toFixed(0)}KB from ${SOURCES.join(', ')}`);
