/**
 * Generates native-boost.css: every design rule re-emitted with an
 * .et_pb_text_inner ancestor prefix, so inside Divi text modules the
 * design system always outranks Divi's own element rules (which sit at
 * class+element specificity and beat the design's bare class rules).
 *
 * Regenerate whenever the source stylesheets change:
 *   node gen-boost.mjs
 * The output is versioned and enqueued last; it cannot drift from the
 * design because it IS the design, re-scoped.
 */
import postcss from 'postcss';
import fs from 'node:fs';
import path from 'node:path';
import { here } from './common.mjs';

const cssDir = path.resolve(here, '../../../divi-child-integration/assets/css');
// Per-source prefixes: home-only stylesheets are scoped to home's own
// sections, mirroring the reference's front-page-only enqueue (their
// global boost leaked home's 54px eyebrows onto every page; 2026-08-24).
const SOURCES = [
  { file: 'pomdr-design.css', prefix: 'body.pom-native' },
  { file: 'pomdr.css', prefix: 'body.pom-native' },
  { file: 'pomdr-home.css', prefix: 'body.pom-native .pg-home' },
  { file: 'paw-trail.css', prefix: 'body.pom-native .pg-home' },
  { file: 'a11y.css', prefix: 'body.pom-native' },
];

// Selectors that must not be re-scoped: chrome, page furniture, Divi's own,
// element-only selectors (no class), and structural roots.
// Uniform boost: chrome-region design rules (footer/nav overrides living
// in pomdr.css and pomdr-design.css) must boost like everything else, or
// the chrome-boost inverts cross-file precedence (native footer tagline
// rendered 29px where the design's 21px override wins on the reference;
// 2026-08-25). Only Divi's own selectors, structural roots, and
// ID-anchored rules (ID already dominates identically on both sides)
// stay unboosted.
const SKIP = /(^|[^\w-])(html|body|:root)([^\w-]|$)|et_pb|et-vb|#site|#main-content|@/;
const ELEMENT_OK = /^(h[1-6]|p|ul|ol|li|blockquote|figure|figcaption|table|th|td|dl|dt|dd|hr|img|picture|strong|em|small)([\s.:>,[]|$)/;

const SYNTH = `
/* Synthetic base, (0,2,0) via :where: beats Divi's element rules inside
   text modules, ties every boosted design class rule and loads first, so
   all boosted rules outrank it. Headings deliberately absent (the design
   ships its own .et_pb_module h1-h6 rules). */
body.pom-native :is(.et_pb_text, .et_pb_code) :where(p, li, ol, ul, blockquote, figcaption) {
  font-size: inherit; line-height: inherit; font-family: inherit;
}
/* Mirror Divi's GLOBAL paragraph padding pair exactly (the reference
   standard): 1em bottom, zeroed on the last p of its parent. Divi's
   module-scoped variant uses :last-child, which misfires when a div
   follows the final paragraph; this restores last-of-type semantics. */
body.pom-native :is(.et_pb_text, .et_pb_code) :where(p) { padding-bottom: 1em; }
body.pom-native :is(.et_pb_text, .et_pb_code) :where(p:not(.has-background):last-of-type) { padding-bottom: 0; }
`;
let out = `/* GENERATED by scripts/native/fidelity/gen-boost.mjs. Do not edit.\n   Design rules re-scoped under body.pom-native: a uniform +1 class that\n   outranks Divi's module element styles while preserving the design's\n   own internal precedence (ancestor-class selectors stay alive). */\n` + SYNTH;

for (const { file, prefix } of SOURCES) {
  const p = path.join(cssDir, file);
  if (!fs.existsSync(p)) continue;
  const root = postcss.parse(fs.readFileSync(p, 'utf8'));
  const boosted = postcss.root();

  root.walkRules((rule) => {
    if (rule.parent && rule.parent.type === 'atrule' && /keyframes/i.test(rule.parent.name)) return;
    const sels = rule.selectors.filter((s) => (s.includes('.') || ELEMENT_OK.test(s.trim())) && !SKIP.test(s));
    if (!sels.length) return;
    const clone = rule.clone();
    clone.selectors = sels.map((s) => `${prefix} ${s.trim()}`);
    // Preserve @media wrappers.
    if (rule.parent && rule.parent.type === 'atrule') {
      const media = postcss.atRule({ name: rule.parent.name, params: rule.parent.params });
      media.append(clone);
      boosted.append(media);
    } else {
      boosted.append(clone);
    }
  });

  out += `\n/* ---- from ${file} ---- */\n` + boosted.toString() + '\n';
}

const dest = path.join(cssDir, 'native-boost.css');
fs.writeFileSync(dest, out);
console.log(`native-boost.css: ${(out.length / 1024).toFixed(0)}KB from ${SOURCES.join(', ')}`);

// Chrome pass: same uniform prefix, own file, enqueued after the content
// boost + page styles; restores the reference's load-order winners for
// nav/action-bar/footer against boosted generic rules (.btn variants).
const CHROME_SKIP = /(^|[^\w-])(html|body|:root)([^\w-]|$)|@/;
let cout = `/* GENERATED by gen-boost.mjs (chrome pass). Do not edit. */
/* Divi's et-critical-inline-css loads late on the REFERENCE and wins
   these element rules by order; the boost outgunned them only on native.
   Mirrored here (loads last), values from the critical block itself. */
/* (0,1,1): ties the boosted element rules and wins by load order, while
   every classed design rule still outranks it, mirroring the critical
   block's (0,0,1)-late position in the reference cascade. */
body.pom-native h3 { font-weight: 700; }
`;
{
  const rootC = postcss.parse(fs.readFileSync(path.join(cssDir, 'pomdr-chrome.css'), 'utf8'));
  const boostedC = postcss.root();
  rootC.walkRules((rule) => {
    if (rule.parent && rule.parent.type === 'atrule' && /keyframes/i.test(rule.parent.name)) return;
    const sels = rule.selectors.filter((s) => !CHROME_SKIP.test(s));
    if (!sels.length) return;
    const clone = rule.clone();
    clone.selectors = sels.map((s) => `body.pom-native ${s.trim()}`);
    if (rule.parent && rule.parent.type === 'atrule') {
      const media = postcss.atRule({ name: rule.parent.name, params: rule.parent.params });
      media.append(clone);
      boostedC.append(media);
    } else {
      boostedC.append(clone);
    }
  });
  cout += boostedC.toString();
}
const destC = path.join(cssDir, 'native-boost-chrome.css');
fs.writeFileSync(destC, cout);
console.log(`native-boost-chrome.css: ${(cout.length / 1024).toFixed(0)}KB`);
