/**
 * Generates native-boost.css: every design rule re-emitted with an
 * .et_pb_text_inner ancestor prefix, so inside Divi text modules the
 * design system always outranks Divi's own element rules (which sit at
 * class+element specificity and beat the design's bare class rules).
 *
 * Regenerate whenever the source stylesheets change:
 *   node gen-boost.mjs
 * The output is versioned and enqueued last; it cannot drift from the
 * design because it IS the design, re-scoped.
 */
import postcss from 'postcss';
import fs from 'node:fs';
import path from 'node:path';
import { here } from './common.mjs';

const cssDir = path.resolve(here, '../../../divi-child-integration/assets/css');
const SOURCES = ['pomdr-design.css', 'pomdr.css'];

// Selectors that must not be re-scoped: chrome, page furniture, Divi's own,
// element-only selectors (no class), and structural roots.
const SKIP = /(^|[^\w-])(html|body|:root)([^\w-]|$)|et_pb|et-vb|#site|#main-content|\.nav\b|\.action-bar|\.footer|\.a11y-|\.skip-link|\.drawer|\.hero\b|\.pt-|@/;
const ELEMENT_OK = /^(h[1-6]|p|ul|ol|li|blockquote|figure|figcaption|table|th|td|dl|dt|dd|hr|img|picture|strong|em|small)([\s.:>,[]|$)/;

const SYNTH = `
/* Synthetic base: Divi's direct element rules inside text modules always
   lose to inheritance; every boosted design rule below overrides this.
   Headings are deliberately absent: the design ships its own
   .et_pb_module h1-h6 rules and a synthetic inherit was proven to beat
   the design's element letter-spacing (fidelity trace 2026-08-19). */
.et_pb_text .et_pb_text_inner :is(p, li, ol, ul, blockquote, figcaption) {
  font-size: inherit; line-height: inherit; font-family: inherit;
}
`;
let out = `/* GENERATED by scripts/native/fidelity/gen-boost.mjs. Do not edit.\n   Design rules re-scoped under .et_pb_text_inner so the design system\n   outranks Divi's text-module element styles inside native pages. */\n` + SYNTH;

for (const file of SOURCES) {
  const p = path.join(cssDir, file);
  if (!fs.existsSync(p)) continue;
  const root = postcss.parse(fs.readFileSync(p, 'utf8'));
  const boosted = postcss.root();

  root.walkRules((rule) => {
    if (rule.parent && rule.parent.type === 'atrule' && /keyframes/i.test(rule.parent.name)) return;
    const sels = rule.selectors.filter((s) => (s.includes('.') || ELEMENT_OK.test(s.trim())) && !SKIP.test(s));
    if (!sels.length) return;
    const clone = rule.clone();
    clone.selectors = sels.map((s) => `.et_pb_text .et_pb_text_inner ${s.trim()}`);
    // Preserve @media wrappers.
    if (rule.parent && rule.parent.type === 'atrule') {
      const media = postcss.atRule({ name: rule.parent.name, params: rule.parent.params });
      media.append(clone);
      boosted.append(media);
    } else {
      boosted.append(clone);
    }
  });

  out += `\n/* ---- from ${file} ---- */\n` + boosted.toString() + '\n';
}

const dest = path.join(cssDir, 'native-boost.css');
fs.writeFileSync(dest, out);
console.log(`native-boost.css: ${(out.length / 1024).toFixed(0)}KB from ${SOURCES.join(', ')}`);
